# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

# Load ActiveAgent tasks
Dir[File.join(File.dirname(__FILE__), '../../lib/tasks/*.rake')].each { |f| load f }
