name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.0
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4"]
        gemfile: [
          "gemfiles/rails8.gemfile",
        ]
        include:
        - ruby: "3.4"
          gemfile: "gemfiles/railsmain.gemfile"
        - ruby: "3.3"
          gemfile: "gemfiles/rails8.gemfile"
        - ruby: "3.2"
          gemfile: "gemfiles/rails7.gemfile"
    steps:
    - uses: actions/checkout@v5
    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Setup database
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        cd test/dummy
        bin/rails db:create
        bin/rails db:migrate
        cd ../..
    - name: Run tests
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: bin/test
